/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_mm_rent_a_car;

import java.util.ArrayList;
import java_mm_rent_a_car.classes.Customer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Melo
 */
// This form is used to the booking
public class Form_CustomersList extends javax.swing.JFrame {

    /**
     * Creates new form Form_CustomersList
     */
    
    Customer customer = new Customer();
    ArrayList<Customer> customersList = customer.customersList();
    
    public Form_CustomersList() {
        initComponents();
        
        // center form
        this.setLocationRelativeTo(null);
        
        // populate jTable
         populateJTable(); 
         
        // set row height jtable
        jTable_customers.setRowHeight(30);
    }
    
    // Method to populate the jTable with customers list
    public void populateJTable() {
        
        // clear arraylist
        customersList.clear();
        
        // populate arraylist
        customersList = customer.customersList();
        
        // jTable columns
        String[] columnsName = {"ID", "Nome", "NIF", "Data Nascimento", "Telefone", "Email", "Endereço"};
        
        // jTable rows
        Object[][] rows = new Object[customersList.size()][columnsName.length];
        
        for(int i = 0; i < customersList.size(); i++) {
            rows[i][0] = customersList.get(i).getId();
            rows[i][1] = customersList.get(i).getFullname();
            rows[i][2] = customersList.get(i).getNif();
            rows[i][3] = customersList.get(i).getBirthdate();
            rows[i][4] = customersList.get(i).getPhone();
            rows[i][5] = customersList.get(i).getEmail();
            rows[i][6] = customersList.get(i).getAddress();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows, columnsName);
        jTable_customers.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel_title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_title1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_customers = new javax.swing.JTable();
        jButton_selectCustomer_list = new javax.swing.JButton();
        jButton_addNewCustomer = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(204, 255, 153));

        jLabel_title.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_title.setText("Reservas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(506, 506, 506)
                .addComponent(jLabel_title)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel_title)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(204, 255, 153));

        jLabel_title1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel_title1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_title1.setText("Lista de Clientes");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_title1)
                .addGap(425, 425, 425))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel_title1)
                .addGap(40, 40, 40))
        );

        jTable_customers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_customersMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_customers);

        jButton_selectCustomer_list.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_selectCustomer_list.setText("Selecionar Cliente");
        jButton_selectCustomer_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selectCustomer_listActionPerformed(evt);
            }
        });

        jButton_addNewCustomer.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_addNewCustomer.setText("Adicionar | Editar | Eliminar");
        jButton_addNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addNewCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_selectCustomer_list, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_addNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_selectCustomer_list, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_addNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_customersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_customersMouseClicked
        // Get selected customer
        int index = jTable_customers.getSelectedRow();
        int id = Integer.valueOf(jTable_customers.getValueAt(index, 0).toString());
        String fullname = jTable_customers.getValueAt(index, 1).toString();
        String nif = jTable_customers.getValueAt(index, 2).toString();
        //Date birthdate = jTable_customers..getValueAt(index, 3);
        String phone = jTable_customers.getValueAt(index, 4).toString();
        String email = jTable_customers.getValueAt(index, 5).toString();
        String address = jTable_customers.getValueAt(index, 6).toString();
        
    }//GEN-LAST:event_jTable_customersMouseClicked

    private void jButton_selectCustomer_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selectCustomer_listActionPerformed
        // Select customer from list
        int index = jTable_customers.getSelectedRow();
        String id = jTable_customers.getValueAt(index, 0).toString();
        String fullname = jTable_customers.getValueAt(index, 1).toString();
        
        // call methode in the Form_Bookings and close this form
        Form_Bookings.displayCustomer(id, fullname);
        
        // close this form
        this.dispose();
    }//GEN-LAST:event_jButton_selectCustomer_listActionPerformed

    private void jButton_addNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addNewCustomerActionPerformed
        // show Form Customers
        Form_Customers frm_ctr = new Form_Customers();
        frm_ctr.setVisible(true);
    }//GEN-LAST:event_jButton_addNewCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_CustomersList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_CustomersList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_CustomersList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_CustomersList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_CustomersList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_addNewCustomer;
    private javax.swing.JButton jButton_selectCustomer_list;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JLabel jLabel_title1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_customers;
    // End of variables declaration//GEN-END:variables
}
