/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_mm_rent_a_car;

import java.util.ArrayList;
import java_mm_rent_a_car.classes.Car;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Melo
 */
public class Form_CarsList extends javax.swing.JFrame {

    /**
     * Creates new form Form_CarsList
     */
    
    Car car = new Car();
    
    
    public Form_CarsList() {
        initComponents();
        
        // center form
        this.setLocationRelativeTo(null);
        
        // populate jTable
         populateJTable();
         
         jTable_cars.setRowHeight(30);
    }
    
    // Method to populate the jTable with car list (all variables)
    public void populateJTable() {
        ArrayList<Car> cars_list = car.carsList();
        
        // jTable columns
        String[] columnsName = {"ID", "Marca", "Modelo", "Matrícula", "Kilómetros", "Combustível", "Cor", "Classe",
                                "Passageiros", "Portas", "Caixa de Velocidades", "Preço", "Ar Cond", "Nome", "Tecto de Abrir",
                                "Bancos Aquecidos", "Sistema de Navegação", "GPS", "Bluetooth", "WIFI"/* */};
        
        // jTable rows
        Object[][] rows = new Object[cars_list.size()][columnsName.length];        
       
        
        for(int i = 0; i < cars_list.size(); i++) {
            rows[i][0] = cars_list.get(i).getId();
            rows[i][1] = cars_list.get(i).getBrand();
            rows[i][2] = cars_list.get(i).getModel(); 
            rows[i][3] = cars_list.get(i).getPlate(); 
            rows[i][4] = cars_list.get(i).getKm(); 
            rows[i][5] = cars_list.get(i).getFuel(); 
            rows[i][6] = cars_list.get(i).getColor();
            rows[i][7] = cars_list.get(i).getClass_(); 
            rows[i][8] = cars_list.get(i).getPassengers();
            rows[i][9] = cars_list.get(i).getDoors(); 
            rows[i][10] = cars_list.get(i).getGearbox(); 
            rows[i][11] = cars_list.get(i).getPrice(); 
            rows[i][12] = cars_list.get(i).getAir_conditioning(); 
            rows[i][13] = cars_list.get(i).getSunroof();
            rows[i][14] = cars_list.get(i).getHeated_seats(); 
            rows[i][15] = cars_list.get(i).getNavigation_system();
            rows[i][16] = cars_list.get(i).getGps(); 
            rows[i][17] = cars_list.get(i).getBluetooth(); 
            rows[i][18] = cars_list.get(i).getWifi();
            /* */
        }
        
        DefaultTableModel model = new DefaultTableModel(rows, columnsName);
        jTable_cars.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_cars = new javax.swing.JTable();
        jLabel_carImage = new javax.swing.JLabel();
        jButton_carEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jPanel9.setBackground(new java.awt.Color(0, 204, 204));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Viaturas Disponíveis");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTable_cars.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTable_cars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_cars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_carsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_cars);

        jLabel_carImage.setOpaque(true);

        jButton_carEdit.setBackground(new java.awt.Color(51, 51, 51));
        jButton_carEdit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_carEdit.setText("Escolher Viatura - Editar | Remover");
        jButton_carEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_carEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton_carEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_carImage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_carImage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_carEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_carsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_carsMouseClicked
        // Get selected brand logo and name
//        int index = jTable_cars.getSelectedRow();
//        int id = Integer.valueOf(jTable_cars.getValueAt(index, 0).toString());
//        Brand brd = brand.getBrandById(id);
//        jLabel_brandName.setText(brd.getName());
//        displayByteImage(jLabel_carImage.getWidth(), jLabel_carImage.getHeight(), brd.getLogo(), jLabel_carImage);
    }//GEN-LAST:event_jTable_carsMouseClicked

    private void jButton_carEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_carEditActionPerformed
        // Take date form selected table row and call the method on Form_Cars
        int index = jTable_cars.getSelectedRow();
        String car_id = jTable_cars.getValueAt(index, 0).toString();
        String brand_id = jTable_cars.getValueAt(index, 1).toString();
        String model = jTable_cars.getValueAt(index, 2).toString();
        String plate = jTable_cars.getValueAt(index, 3).toString();
        String km = jTable_cars.getValueAt(index, 4).toString();
        String fuel = jTable_cars.getValueAt(index, 5).toString();
        String color = jTable_cars.getValueAt(index, 6).toString();
        String class_ = jTable_cars.getValueAt(index, 7).toString();
        String passengers = jTable_cars.getValueAt(index, 8).toString();
        String doors = jTable_cars.getValueAt(index, 9).toString();
        String gearbox = jTable_cars.getValueAt(index, 10).toString();
        String price = jTable_cars.getValueAt(index, 11).toString();
        
        String air_cond = jTable_cars.getValueAt(index, 12).toString();
        String sunroof = jTable_cars.getValueAt(index, 13).toString();
        String heated_seats = jTable_cars.getValueAt(index, 14).toString();
        String navigation_system = jTable_cars.getValueAt(index, 15).toString();
        String gps = jTable_cars.getValueAt(index, 16).toString();
        String bluetooth = jTable_cars.getValueAt(index, 17).toString();
        String wifi = jTable_cars.getValueAt(index, 18).toString();
        
        // call the form and post id
        Form_Cars.displayCars(car_id, brand_id, model, plate, km, fuel, color,class_,
                passengers, doors, gearbox, price, air_cond, sunroof, heated_seats,
                navigation_system, gps, bluetooth, wifi);
        
        // close this form
        this.dispose();
    }//GEN-LAST:event_jButton_carEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_CarsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_CarsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_CarsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_CarsList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_CarsList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_carEdit;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_carImage;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_cars;
    // End of variables declaration//GEN-END:variables
}
